### ISSUE TITLE
Date doesn't get serialized

### ISSUE THREAD

**Issue by ManikaAgarwal** [cs2103jan2015-w14-3j/main#101]
With regards to the file not being read, I think there is a problem with the serialization. In  f2f36920828c8ce6f9af5076901b3b0b299778d1, I changed registerLocalDate() to registerDateTime() since the date/time are now being stored using DateTime (change back if you feel it's incorrect). It now throws an UnsupportedOperationException. I can't figure out which operation is unsupported. Apparently it's JsonElement.getAsString(), but I can't figure out why.

**Comment by mauris** [comment]
@ManikaAgarwal I just ran the app again. It seems like it is working after your fix.

I am now able to add a task with date/time specified, exit the app, and start the app again without the app crashing.
