### ISSUE TITLE
Make tasma window movable.

### ISSUE THREAD

**Issue by ManikaAgarwal** [cs2103jan2015-w14-3j/main#112]
The window shows up in the middle of the screen, but cannot be moved around the laptop screen.

**Comment by mauris** [comment]
it is supposed to hide when you are not using it. not supposed to be moved around :D

**Comment by ManikaAgarwal** [comment]
Suppose I want to enter a task related to something I have on screen. If the tasma window covers that stuff when I open it, I am gonna have to first note down the details somewhere else, and then open tasma and enter the task in, which seems a bit of a hassle to me. On the other hand, if I can just move the tasma window around, I don't need to note down the task details somewhere else.

**Comment by mauris** [comment]
restored the title bar so that the window is now movable
