### ISSUE TITLE
Fix overdue

### ISSUE THREAD

**Issue by ManikaAgarwal** [cs2103jan2015-w14-3j/main#128]
Overdue tasks don't show in a separate overdue section as they're supposed to.

**Comment by ManikaAgarwal** [comment]
Or are they supposed to just be red? Even so, this feature isn't working.

**Comment by mauris** [comment]
![screenshot 2015-04-06 23 10 23](https://cloud.githubusercontent.com/assets/996939/7006231/231757f8-dcb2-11e4-88a3-73b473e21b98.png)
seems like the red colour is working for me. the task has to be before today (because of the time issue)

**Comment by ManikaAgarwal** [comment]
So aren't we planning to fix the time issue??
