### ISSUE TITLE
Invalid Date Exception

### ISSUE THREAD

**Issue by mauris** [cs2103jan2015-w14-3j/main#90]
@ManikaAgarwal, i'm facing some issues with the invalid date exception thrown from the parser class.

Test command:

```
add test tomorrow on 5 mar 2015
```

Seems like the code does not recognise "5 mar 2015" as a valid date?

**Comment by ManikaAgarwal** [comment]
Yes, it currently only accepts dates entered in the dd.-mm.-yy format. Will be implementing the format you have stated later.

**Comment by mauris** [comment]
understood (:

**Comment by mauris** [comment]
@ManikaAgarwal i think wrt this issue, if there is a problem parsing the date/time, we should leave the datetime and assume that it is not a date/time so that we can add into the task list.

**Comment by ManikaAgarwal** [comment]
Hmmm...okay!
